import Link from "next/link";

export const metadata = {
  title: "Terms of Service",
  description: "Toddler Trip terms of service — rules and guidelines for using our family travel planner.",
};

const INK = "#1C2B33";
const STONE = "#8A9BA5";
const MIST = "#F0EDE8";
const CLOUD = "#FAFAF7";
const SUNSET = "#E8643A";

export default function TermsPage() {
  return (
    <div style={{ fontFamily: "'Nunito', sans-serif", background: CLOUD, minHeight: "100vh", color: INK }}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700;800;900&family=Nunito:wght@400;600;700;800&display=swap');`}</style>

      <nav style={{ borderBottom: `1px solid ${MIST}`, padding: "0 24px", height: 58, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <Link href="/" style={{ display: "flex", alignItems: "center", gap: 9, textDecoration: "none" }}>
          <span style={{ fontSize: 24 }}>🧳</span>
          <span style={{ fontFamily: "'Playfair Display', serif", fontSize: 17, fontWeight: 800, color: INK }}>Toddler Trip</span>
        </Link>
        <Link href="/plan" style={{ padding: "8px 20px", borderRadius: 10, border: "none", background: `linear-gradient(135deg, ${SUNSET}, #F09A3A)`, color: "#fff", fontSize: 13, fontWeight: 800, textDecoration: "none" }}>
          Plan a Trip &rarr;
        </Link>
      </nav>

      <main style={{ maxWidth: 680, margin: "0 auto", padding: "56px 24px 80px" }}>
        <h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: 36, fontWeight: 800, marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ fontSize: 13, color: STONE, fontWeight: 600, marginBottom: 32 }}>Last updated: March 13, 2026</p>

        <div style={{ fontSize: 15, lineHeight: 1.8, color: STONE, fontWeight: 600 }}>
          <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: 20, fontWeight: 800, color: INK, marginTop: 28, marginBottom: 10 }}>1. Service description</h2>
          <p>Toddler Trip (&ldquo;the Service&rdquo;) is a free web application that generates family travel itineraries using AI. The Service is provided &ldquo;as is&rdquo; without warranties of any kind.</p>

          <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: 20, fontWeight: 800, color: INK, marginTop: 28, marginBottom: 10 }}>2. User accounts</h2>
          <p>You may create an account to save trips. You are responsible for keeping your login credentials secure. You must be at least 18 years old to create an account.</p>

          <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: 20, fontWeight: 800, color: INK, marginTop: 28, marginBottom: 10 }}>3. AI-generated content</h2>
          <p>Itineraries, activity suggestions, and packing lists are generated by AI and should be treated as suggestions. Always verify details like opening hours, admission prices, age restrictions, and safety considerations independently before your trip.</p>

          <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: 20, fontWeight: 800, color: INK, marginTop: 28, marginBottom: 10 }}>4. Affiliate links</h2>
          <p>Some links on Toddler Trip are affiliate links. When you purchase through these links, we may earn a commission at no extra cost to you. Affiliate relationships do not influence our activity recommendations.</p>

          <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: 20, fontWeight: 800, color: INK, marginTop: 28, marginBottom: 10 }}>5. Limitation of liability</h2>
          <p>Toddler Trip is not liable for any damages arising from the use of AI-generated travel plans. Travel involves inherent risks, especially with children. Use your best judgment and consult local sources for safety information.</p>

          <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: 20, fontWeight: 800, color: INK, marginTop: 28, marginBottom: 10 }}>6. Changes to these terms</h2>
          <p>We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>

          <h2 style={{ fontFamily: "'Playfair Display', serif", fontSize: 20, fontWeight: 800, color: INK, marginTop: 28, marginBottom: 10 }}>7. Contact</h2>
          <p>Questions about these terms? Email <a href="mailto:hello@toddlertrip.com" style={{ color: "#0B7A8E", fontWeight: 700 }}>hello@toddlertrip.com</a>.</p>
        </div>
      </main>
    </div>
  );
}
